# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08a8a76a1ae669e22e873c59ff9f2aebd98879a536d29d1b42a41c2bd9b2829c9d776954a6615c71421255b902ed2bb83263c625f647114ca502fda7d7e2e2e0

test:
  secret_key_base: 85ea2db4ed58160f113e8b30398a57a5a7d2957173677e16d42ed3590642eba077513889b86cdae01f670844d5370389e9d67347b77271a14adcdfdaa1a54c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
