# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbe77bff53d621dac77ed2833cdc70de8b872035a6487489443455a7a9b8b49c94f2e7e10f8cad2dd3d85a758977ac308af3b8a6d99b7ea0d6c8bb0941379fa5

test:
  secret_key_base: 44755bde7bc323034e93f12147b7e6bd78dc704a40e7bcfaf820f34ff6795f171fe33c86521940880d2d61559c53bd28998c819904c4158b9da24e91040e6c9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
