# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be775e5058014efe21e2db7da6e2adce33f3b6d9282812c6f08319b567857592b6a6d9ab02d4c5eec5e62191319124342ad8f9aea38c62ae149cd57758cdb35c

test:
  secret_key_base: e628e55e819a18fa25a54b3fe13daa30a79f0b348a5db5e8c2adaba1759178fb1899cc54dc0c7b930f5b659cfcd1c177bbcd6095213c75bd821651bf77ff3634

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
