# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be66bbf0a9f8c658a02f27c2a52a228261e38d02584cc2ccad8707799f0c680bf8c411cb22a0547393b56e058b8b1c667eabb3fb0c823ea57af9fe8ec7130883

test:
  secret_key_base: 3bbc63d87629ea71f7898f570dcda959f1c8021c80aa5d97321d3543501b745bb5857d7934e446c550324bca0e6d0a1d2958f8e72524e9d99a09c27c7bfc4e8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
